input_select_harmony:
  alias: "Start activity from input select"
  sequence:
  - service: remote.turn_on
    data_template:
      entity_id: remote.living_room_tv
      activity: >
        {% if is_state("input_select.living_room_tv", "Power Off") %}
            -1
        {% elif is_state("input_select.living_room_tv", "Watch TV") %}
            27367873
        {% elif is_state("input_select.living_room_tv", "Watch Apple TV") %}
            27368265
        {% elif is_state("input_select.living_room_tv", "Watch Shield TV") %}
            27368220
        {% elif is_state("input_select.living_room_tv", "Watch Smart TV") %}
            27368631
        {% elif is_state("input_select.living_room_tv", "Listen to Music") %}
            27368467
        {% endif %}
