- alias: Living Room Lights Off
  trigger:
  - entity_id: binary_sensor.living_room_motion
    platform: state
    from: 'on'
    to: 'off'
    for:
      hours: 0
      minutes: 15
      seconds: 0
  action:
  - service: light.turn_off
    entity_id: light.living_room
    data:
      transition: 15

- alias: Living Room Lights On
  trigger:
  - entity_id: binary_sensor.living_room_motion
    platform: state
    from: 'off'
    to: 'on'
  condition:
    condition: state
    entity_id: light.living_room
    state: 'off'
  action:
  - service: light.hue_activate_scene
    data_template:
      group_name: Living Room
      scene_name: '{{ states.sensor.day_phase.state }}'

- alias: Living Room Lights Update
  trigger:
  - entity_id: sensor.day_phase
    platform: state
  condition:
    condition: state
    entity_id: light.living_room
    state: 'on'
  action:
  - service: light.hue_activate_scene
    data_template:
      group_name: Living Room
      scene_name: '{{ states.sensor.day_phase.state }}'
