language: python
python:
  - '3.5'
install:
  - 'pip3 install homeassistant'
  - 'mv secrets.yaml.sample secrets.yaml'
script:
  - 'hass -c . --script check_config | tee check.output'
  - '! less check.output | grep -q "Failed config"'

