language: python
python:
  - "3.4"
install:
  - pip3 install homeassistant
script:
  - hass -c ./home-assistant/config --script check_config
before_install:
  - mv ./home-assistant/config/secrets.yaml.sample ./home-assistant/config/secrets.yaml
