homeassistant:
  name: Home
  latitude: ***REMOVED***
  longitude: ***REMOVED***
  elevation: 150
  unit_system: metric
  time_zone: Europe/London

  customize: !include_dir_merge_named customize
  packages: !include_dir_merge_named packages

http:
  api_password: !secret hass_password
  base_url: !secret hass_base_url
  trusted_networks:
  - 127.0.0.1
  - 192.168.0.0/24

duckdns:
  domain: !secret duckdns_domain
  access_token: !secret duckdns_token

# Enablers
browser:
config:
conversation:
discovery:
frontend:
  javascript_version: latest
ios:
sun:
updater:
  include_used_components: true

recorder: !include recorder.yaml
history:
logbook:

tts:
  platform: amazon_polly
  aws_access_key_id: !secret aws_access_key_id
  aws_secret_access_key: !secret aws_secret_access_key
  region_name: eu-west-1
  text_type: text
  voice: Brian

# Includes
automation: !include_dir_merge_list automation
binary_sensor: !include_dir_merge_list binary_sensor
climate: !include_dir_merge_list climate
group: !include_dir_merge_named group
# input_select: !include_dir_merge_named input_select
# input_boolean: !include_dir_merge_named input_boolean
light: !include_dir_merge_list light
media_player: !include_dir_merge_list media_player
nest: !include nest.yaml
remote: !include_dir_merge_list remote
scene: !include_dir_merge_list scene
script: !include_dir_merge_named script
sensor: !include_dir_merge_list sensor
# shell_command: !include_dir_merge_named shell_command
switch: !include_dir_merge_list switch
# timer: !include_dir_merge_named timer
weather: !include_dir_merge_list weather
