homeassistant:
  name: Home
  latitude: !secret zone_home_lat
  longitude: !secret zone_home_long
  elevation: 150
  unit_system: metric
  time_zone: Europe/London

  customize: !include_dir_merge_named customize
  packages: !include_dir_merge_named packages

# Enablers
browser:
cloud:
config:
conversation:
discovery:
frontend:
  javascript_version: latest
ios:
map:
sun:
updater:
  include_used_components: true

# History
recorder:
  db_url: !secret db_connection
  purge_interval: 1
  purge_keep_days: 14
  exclude:
    entities:
    - sensor.date
history:
  include:
    entities:
    - light.bedroom
    - light.den
    - light.dressing_room
    - light.guest_bedroom
    - light.hallways
    - light.kitchen
    - light.living_room
    - light.porch
    - sensor.average_load_1m
    - sensor.average_load_5m
    - sensor.average_load_15m
logbook:
  exclude:
    domains:
    - group
    entities:
    - binary_sensor.kitchen_motion
    - binary_sensor.living_room_motion
    - binary_sensor.entrance_hall_motion
    - sensor.log_db_file_size
    - sensor.cpu_temp
    - sensor.average_load_15m
    - sensor.since_last_boot

# external links
weblink:
  entities:
  - name: Sky Router
    icon: mdi:ethernet
    url: http://192.168.0.1
  - name: BT WiFi
    icon: mdi:router-wireless
    url: http://mybtdevice.home
  - name: Travis
    icon: mdi:worker
    url: https://travis-ci.org/danrspencer/hass-config

# Text To Speech
tts:
  platform: amazon_polly
  aws_access_key_id: !secret aws_access_key_id
  aws_secret_access_key: !secret aws_secret_access_key
  region_name: eu-west-1
  text_type: text
  voice: Brian

# Device Tracking
zone:
  - zone:
    name: Home
    latitude: !secret zone_home_lat
    longitude: !secret zone_home_long
    radius: 250

  - zone 2:
    name: Work
    latitude: !secret zone_l_work_lat
    longitude: !secret zone_l_work_long
    icon: mdi:briefcase

  - zone 3:
    name: Work
    latitude: !secret zone_d_work_lat
    longitude: !secret zone_d_work_long
    icon: mdi:briefcase

http:
  api_password: !secret hass_password
  base_url: !secret hass_base_url
  trusted_networks:
  - 127.0.0.1
  - 192.168.0.0/24

device_tracker:
  - platform: nmap_tracker
    hosts:
      - 192.168.0.6
      - 192.168.0.9

duckdns:
  domain: !secret duckdns_domain
  access_token: !secret duckdns_token

# Components
automation: !include_dir_merge_list automation
binary_sensor: !include_dir_merge_list binary_sensor
climate: !include_dir_merge_list climate
group: !include_dir_merge_named group
# input_select: !include_dir_merge_named input_select
input_boolean: !include_dir_merge_named input_boolean
light: !include_dir_merge_list light
media_player: !include_dir_merge_list media_player
nest: !include nest.yaml
# remote: !include_dir_merge_list remote
scene: !include_dir_merge_list scene
script: !include_dir_merge_named script
sensor: !include_dir_merge_list sensor
# shell_command: !include_dir_merge_named shell_command
switch: !include_dir_merge_list switch
# timer: !include_dir_merge_named timer
weather: !include_dir_merge_list weather
