- platform: rest
  resource: https://api.travis-ci.org/repos/danrspencer/hass-config/builds
  headers:
    Accept: application/vnd.travis-ci.2+json
  value_template: '{{ value_json.builds[0].state }}'
  name: 'Travis Build Status'

- platform: steam_online
  api_key: !secret steam_key
  accounts:
    - 76561197972831800

- platform: destiny2
  membership_type: 2
  destiny_membership_id: 4611686018428481758
  api_key: !secret destiny2_api_key
