- alias: Hallways Lights On
  trigger:
  - entity_id: binary_sensor.entrance_hall_motion
    platform: state
    from: 'off'
    to: 'on'
  - entity_id: binary_sensor.top_floor_motion
    platform: state
    from: 'off'
    to: 'on'
  condition:
    condition: state
    entity_id: light.hallways
    state: 'off'
  action:
  - service: hue.hue_activate_scene
    data_template:
      group_name: Hallways
      scene_name: '{{ states.sensor.day_phase.state }}'

- alias: Hallways Lights Update
  trigger:
  - entity_id: sensor.day_phase
    platform: state
  condition:
    condition: state
    entity_id: light.hallways
    state: 'on'
  action:
  - service: hue.hue_activate_scene
    data_template:
      group_name: Hallways
      scene_name: '{{ states.sensor.day_phase.state }}'
