- alias: Hallways Lights Off
  trigger:
  - entity_id: binary_sensor.house_motion
    platform: state
    from: 'on'
    to: 'off'
    for:
      hours: 0
      minutes: 30
      seconds: 0
  action:
  - service: light.turn_off
    entity_id: light.hallways
    data:
      transition: 15

- alias: Hallways Lights On
  trigger:
  - entity_id: binary_sensor.entrance_hall_motion
    platform: state
    from: 'off'
    to: 'on'
  condition:
    condition: state
    entity_id: light.hallways
    state: 'off'
  action:
  - service: hue.hue_activate_scene
    data_template:
      group_name: Hallways
      scene_name: '{{ states.sensor.day_phase.state }}'

- alias: Hallways Lights On From Top Floor
  trigger:
  - entity_id: binary_sensor.top_floor_motion
    platform: state
    from: 'off'
    to: 'on'
  condition:
    condition: and
    conditions:
    - condition: state
      entity_id: light.hallways
      state: 'off'
    - condition: state
      entity_id: input_boolean.top_floor_lights_auto
      state: 'off'
  action:
  - service: hue.hue_activate_scene
    data_template:
      group_name: Hallways
      scene_name: '{{ states.sensor.day_phase.state }}'

- alias: Hallways Lights Update
  trigger:
  - entity_id: sensor.day_phase
    platform: state
  condition:
    condition: state
    entity_id: light.hallways
    state: 'on'
  action:
  - service: hue.hue_activate_scene
    data_template:
      group_name: Hallways
      scene_name: '{{ states.sensor.day_phase.state }}'
