- alias: Living Room Lights Off
  trigger:
  - entity_id: binary_sensor.living_room_motion
    platform: state
    from: 'on'
    to: 'off'
    for:
      hours: 0
      minutes: 15
      seconds: 0
  action:
  - service: light.turn_off
    entity_id: light.living_room
    data:
      transition: 15
  - service: switch.turn_off
    entity_id: switch.living_room_fairy_lights

- alias: Living Room Lights On
  trigger:
  - entity_id: binary_sensor.living_room_motion
    platform: state
    from: 'off'
    to: 'on'
  condition:
    condition: state
    entity_id: light.living_room
    state: 'off'
  action:
  - service: hue.hue_activate_scene
    data_template:
      group_name: Living Room
      scene_name: '{{ states.sensor.day_phase.state }}'
  - service_template: >
      {% if states.sensor.day_phase.state == 'Evening' or states.sensor.day_phase.state == 'Night' %}
        switch.turn_on
      {% endif %}
    entity_id: switch.living_room_fairy_lights

- alias: Living Room Lights Update
  trigger:
  - entity_id: sensor.day_phase
    platform: state
  condition:
    condition: state
    entity_id: light.living_room
    state: 'on'
  action:
  - service: hue.hue_activate_scene
    data_template:
      group_name: Living Room
      scene_name: '{{ states.sensor.day_phase.state }}'
  - service_template: >
      {% if states.sensor.day_phase.state == 'Evening' or states.sensor.day_phase.state == 'Night' %}
        switch.turn_on
      {% endif %}
    entity_id: switch.living_room_fairy_lights
