- platform: template
  switches:
    living_room_tv:
      friendly_name: Living Room TV
      value_template: '{{ states.sensor.living_room_tv.state != "PowerOff" }}'
      entity_id: sensor.living_room_tv
      turn_on:
        service:  remote.turn_on
        data_template:
          entity_id: remote.living_room_tv
          activity: '{{ states.input_select.living_room_tv.state }}'
      turn_off:
        service: remote.turn_off
        entity_id: remote.living_room_tv

    playstation_4:
      friendly_name: PlayStation 4
      value_template: '{{ states.media_player.playstation_4.state != "off" }}'
      entity_id: media_player.playstation_4
      turn_on:
        service:  media_player.turn_on
        entity_id: media_player.playstation_4
      turn_off:
        service: media_player.turn_off
        entity_id: media_player.playstation_4

    dressing_room_light:
      friendly_name: Dressing Room Light
      value_template: '{{ is_state('light.dressing_room', 'on') }}'
      entitiy_id: light.dressing_room
      turn_on:
        service: light.hue_activate_scene
        data_template:
          group_name: Dressing Room
          scene_name: '{{ states.sensor.day_phase.state }}'
      turn_off:
        service: light.turn_off
        entity_id: light.dressing_room

- platform: tplink
  name: Living Room Light Tree
  host: 192.168.0.42

- platform: tplink
  name: Kitchen Heater
  host: 192.168.0.48
