- platform: template
  switches:
    living_room_tv:
      friendly_name: Living Room TV
      value_template: '{{ states.remote.living_room_tv.attributes.current_activity != "PowerOff" }}'
      entity_id: sensor.living_room_tv
      turn_on:
        service:  remote.turn_on
        data_template:
          entity_id: remote.living_room_tv
          activity: '{{ states.input_select.living_room_tv.state }}'
      turn_off:
        service: remote.turn_off
        entity_id: remote.living_room_tv

- platform: command_line
  switches:
    hyperion:
      friendly_name: TV Ambilight
      command_on: '/config/bash_scripts/hyperion/on.sh'
      command_off: '/config/bash_scripts/hyperion/off.sh'
      command_state: '/config/bash_scripts/hyperion/status.sh'

- platform: tplink
  name: Living Room Light Tree
  host: 192.168.0.42
