- platform: tplink
  name: Living Room Light Tree
  host: 192.168.0.42

- platform: tplink
  name: Living Room Buddha
  host: 192.168.0.48

- platform: tplink
  name: Garage Heater
  host: 192.168.0.66