- platform: rest
  resource: !secret hue_kitchen_light
  value_template: '{{ value_json.state.lightlevel }}'
  unit_of_measurement: Lux
  name: 'Kitchen Light'

- platform: rest
  resource: !secret hue_kitchen_temperature
  value_template: '{{ value_json.state.temperature | float / 100 }}'
  unit_of_measurement: °C
  name: 'Kitchen Temperature'

- platform: rest
  resource: !secret hue_living_room_light
  value_template: '{{ value_json.state.lightlevel }}'
  unit_of_measurement: Lux
  name: 'Living Room Light'

- platform: rest
  resource: !secret hue_living_room_temperature
  value_template: '{{ value_json.state.temperature | float / 100 }}'
  unit_of_measurement: °C
  name: 'Living Room Temperature'

- platform: rest
  resource: !secret hue_entrance_hall_light
  value_template: '{{ value_json.state.lightlevel }}'
  unit_of_measurement: Lux
  name: 'Entrance Hall Light'

- platform: rest
  resource: !secret hue_entrance_hall_temperature
  value_template: '{{ value_json.state.temperature | float / 100 }}'
  unit_of_measurement: °C
  name: 'Entrance Hall Temperature'
