dphone:
  hide_if_away: false
  icon:
  mac: !secret dphone_mac
  name: Dan
  picture: !secret dan_profile
  track: true
  vendor:

laurens_iphone:
  hide_if_away: false
  icon:
  mac: !secret laurens_iphone_mac
  name: Lauren
  picture: !secret lauren_profile
  track: true
  vendor:
