default_view:
  view: yes
  entities:
  - scene.everything_off

lights:
  name: Lights
  icon: mdi:lightbulb
  view: yes
  entities:
  - scene.everything_off
  - group.living_room_lights
  - group.kitchen_lights
  - group.top_floor_lights
  - group.hallways_lights

media:
  name: Media
  icon: mdi:speaker-wireless
  view: yes
  entities:
  - media_player.everything
  - remote.harmony_hub
  - media_player.living_room_tv
  - media_player.living_room
  - media_player.ground_floor
  - media_player.hear_go
  - media_player.kitchen
  - media_player.top_floor
  - media_player.den
  - media_player.bedroom
  - media_player.dressing_room

house:
  name: House
  icon: mdi:home-modern
  view: yes
  entities:
  - group.house_climate
  - group.network

outside:
  name: Outside
  icon: mdi:weather-partlycloudy
  view: yes
  entities:
  - group.misc_weather
  - group.dark_sky
  - group.met_office
  - weather.met_office_whitecote
  - weather.openweathermap
