house_climate:
  name: House Climate
  entities:
  - sensor.house_thermostat_target
  - sensor.house_thermostat_temperature
  - sensor.house_thermostat_humidity
  - sensor.entrance_hall_temperature
  - sensor.kitchen_temperature
  - sensor.house_thermostat_operation_mode
  - binary_sensor.house_thermostat_online

network:
  name: Network
  entities:
  - sensor.fastcom_download
  - sensor.speedtest_download
  - sensor.speedtest_upload
  - sensor.speedtest_ping
