- alias: Kitchen Motion Start Timer
  trigger:
  - entity_id: binary_sensor.kitchen_motion
    platform: state
    from: 'off'
    to: 'on'
  action:
  - service: timer.start
    data:
      entity_id: timer.kitchen_motion

- alias: Kitchen Motion Reset Timer
  trigger:
  - entity_id: light.kitchen
    platform: state
    from: 'on'
    to: 'off'
    for:
      hours: 0
      minutes: 0
      seconds: 30
  action:
  - service: timer.cancel
    data:
      entity_id: timer.kitchen_motion

- alias: Kitchen Lights Off
  trigger:
  - entity_id: timer.kitchen_motion
    platform: state
    from: 'active'
    to: 'idle'
  action:
  - service: light.turn_off
    entity_id: light.kitchen
    data:
      transition: 15

- alias: Kitchen Lights On
  trigger:
  - entity_id: timer.kitchen_motion
    platform: state
    from: 'idle'
    to: 'active'
  action:
  - service: light.hue_activate_scene
    data_template:
      group_name: Kitchen
      scene_name: '{{ states.sensor.day_phase.state }}'

- alias: Kitchen Lights Update
  trigger:
  - entity_id: sensor.day_phase
    platform: state
  condition:
    condition: state
    entity_id: light.kitchen
    state: 'on'
  action:
  - service: light.hue_activate_scene
    data_template:
      group_name: Kitchen
      scene_name: '{{ states.sensor.day_phase.state }}'
