- platform: generic_thermostat
  name: Kitchen
  heater: switch.kitchen_heater
  target_sensor: sensor.kitchen_temperature
  min_temp: 10
  max_temp: 20
  target_temp: 12
  tolerance: 0
  operation_mode: off