# TV Watched
- platform: history_stats
  name: Total TV Watched Last Week
  entity_id: switch.living_room_tv
  state: 'on'
  start: >
    {{ as_timestamp(
        now().replace(hour=0).replace(minute=0).replace(second=0)
      ) - (now().weekday() + 7) * 86400
    }}
  end: >
    {{ as_timestamp(
        now().replace(hour=0).replace(minute=0).replace(second=0)
      ) - now().weekday() * 86400
    }}

- platform: history_stats
  name: Total TV Watched This Week
  entity_id: switch.living_room_tv
  state: 'on'
  start: >
    {{ as_timestamp(
        now().replace(hour=0).replace(minute=0).replace(second=0)
      ) - now().weekday() * 86400
    }}
  end: '{{ now() }}'

# Sky TV Watched
- platform: history_stats
  name: Sky TV Watched Last Week
  entity_id: remote.living_room_tv
  state: 'Watch TV'
  start: >
    {{ as_timestamp(
        now().replace(hour=0).replace(minute=0).replace(second=0)
      ) - (now().weekday() + 7) * 86400
    }}
  end: >
    {{ as_timestamp(
        now().replace(hour=0).replace(minute=0).replace(second=0)
      ) - now().weekday() * 86400
    }}

- platform: history_stats
  name: Sky TV Watched This Week
  entity_id: remote.living_room_tv
  state: 'Watch TV'
  start: >
    {{ as_timestamp(
        now().replace(hour=0).replace(minute=0).replace(second=0)
      ) - now().weekday() * 86400
    }}
  end: '{{ now() }}'

# Shield TV
- platform: history_stats
  name: Sky TV Watched Last Week
  entity_id: remote.living_room_tv
  state: 'Watch Shield TV'
  start: >
    {{ as_timestamp(
        now().replace(hour=0).replace(minute=0).replace(second=0)
      ) - (now().weekday() + 7) * 86400
    }}
  end: >
    {{ as_timestamp(
        now().replace(hour=0).replace(minute=0).replace(second=0)
      ) - now().weekday() * 86400
    }}

- platform: history_stats
  name: Sky TV Watched This Week
  entity_id: remote.living_room_tv
  state: 'Watch Shield TV'
  start: >
    {{ as_timestamp(
        now().replace(hour=0).replace(minute=0).replace(second=0)
      ) - now().weekday() * 86400
    }}
  end: '{{ now() }}'

# Music
- platform: history_stats
  name: Music Listened To Last Week
  entity_id: media_player.speakers
  state: 'playing'
  start: >
    {{ as_timestamp(
        now().replace(hour=0).replace(minute=0).replace(second=0)
      ) - (now().weekday() + 7) * 86400
    }}
  end: >
    {{ as_timestamp(
        now().replace(hour=0).replace(minute=0).replace(second=0)
      ) - now().weekday() * 86400
    }}

- platform: history_stats
  name: Music Listened To This Week
  entity_id: media_player.speakers
  state: 'playing'
  start: >
    {{ as_timestamp(
        now().replace(hour=0).replace(minute=0).replace(second=0)
      ) - now().weekday() * 86400
    }}
  end: '{{ now() }}'

# PlayStation 4
- platform: history_stats
  name: PlayStation 4 Played Last Week
  entity_id: switch.playstation_4
  state: 'on'
  start: >
    {{ as_timestamp(
        now().replace(hour=0).replace(minute=0).replace(second=0)
      ) - (now().weekday() + 7) * 86400
    }}
  end: >
    {{ as_timestamp(
        now().replace(hour=0).replace(minute=0).replace(second=0)
      ) - now().weekday() * 86400
    }}

- platform: history_stats
  name: PlayStation 4 Played This Week
  entity_id: switch.playstation_4
  state: 'on'
  start: >
    {{ as_timestamp(
        now().replace(hour=0).replace(minute=0).replace(second=0)
      ) - now().weekday() * 86400
    }}
  end: '{{ now() }}'

# Kitchen Heater
# - platform: history_stats
#   name: Kitchen Heater ON Last Week
#   entity_id: switch.kitchen_heater
#   state: 'on'
#   start: >
#     {{ as_timestamp(
#         now().replace(hour=0).replace(minute=0).replace(second=0)
#       ) - (now().weekday() + 7) * 86400
#     }}
#   end: >
#     {{ as_timestamp(
#         now().replace(hour=0).replace(minute=0).replace(second=0)
#       ) - now().weekday() * 86400
#     }}
#
# - platform: history_stats
#   name: Kitchen Heater ON This Week
#   entity_id: switch.kitchen_heater
#   state: 'on'
#   start: >
#     {{ as_timestamp(
#         now().replace(hour=0).replace(minute=0).replace(second=0)
#       ) - now().weekday() * 86400
#     }}
#   end: '{{ now() }}'
#
# - platform: history_stats
#   name: Kitchen Heater ON Today
#   entity_id: switch.kitchen_heater
#   state: 'on'
#   start: >
#     {{ now().replace(hour=0).replace(minute=0).replace(second=0) }}
#   end: '{{ now() }}'
