- platform: template
  sensors:
    living_room_tv:
      value_template: '{{ sensor.living_room_tv }}'
      friendly_name: 'Living Room TV'

- platform: rest
  resource: https://api.travis-ci.org/repos/danrspencer/hass-config/builds
  headers:
    Accept: application/vnd.travis-ci.2+json
  value_template: '{{ value_json.builds[0].state }}'
  name: 'Travis Build Status'
