- platform: rest
  resource: https://api.travis-ci.org/repos/danrspencer/hass-config/builds
  headers:
    Accept: application/vnd.travis-ci.2+json
  value_template: '{{ value_json.builds[0].state }}'
  name: 'Travis Build Status'

- platform: steam_online
  api_key: !secret steam_key
  accounts:
    - 76561197972831800

- platform: command_line
  name: Destiny 2 Subclass Element
  command: /config/bash_scripts/destiny2_subclass.sh
  scan_interval: 30
