- platform: template
  sensors:
    day_phase:
      value_template: >
        {% if now() > now().replace(hour=5).replace(minute=0).replace(second=0) and
            now() < now().replace(hour=9).replace(minute=0).replace(second=0) %}
            Morning
        {%- elif states.sun.sun.state == "above_horizon" -%}
            Day
        {%- elif now() < now().replace(hour=22).replace(minute=0).replace(second=0) -%}
            Evening
        {%- else -%}
            Night
        {%- endif %}
      friendly_name: 'Day Phase'
    living_room_tv:
      value_template: '{{ states.remote.living_room_tv.attributes.current_activity }}'
      friendly_name: 'Living Room TV'

- platform: rest
  resource: https://api.travis-ci.org/repos/danrspencer/hass-config/builds
  headers:
    Accept: application/vnd.travis-ci.2+json
  value_template: '{{ value_json.builds[0].state }}'
  name: 'Travis Build Status'

- platform: steam_online
  api_key: !secret steam_key
  accounts:
    - 76561197972831800
