- platform: template
  sensors:
    day_phase:
      friendly_name: 'Day Phase'
      value_template: >
        {% if now() > now().replace(hour=5).replace(minute=0).replace(second=0) and
            now() < now().replace(hour=6).replace(minute=15).replace(second=0) %}
            Early Morning
        {% elif now() > now().replace(hour=6).replace(minute=15).replace(second=0) and
            now() < now().replace(hour=9).replace(minute=0).replace(second=0) %}
            Morning
        {% elif states.sun.sun.state == "above_horizon" %}
            Day
        {% elif now() < now().replace(hour=21).replace(minute=0).replace(second=0) and
            now() > now().replace(hour=9).replace(minute=0).replace(second=0) %}
            Evening
        {% else %}
            Night
        {% endif %}
      icon_template: >
        {% if now() > now().replace(hour=5).replace(minute=0).replace(second=0) and
            now() < now().replace(hour=9).replace(minute=0).replace(second=0) %}
            mdi:weather-sunset-up
        {% elif states.sun.sun.state == "above_horizon" %}
            mdi:weather-sunny
        {% elif now() < now().replace(hour=21).replace(minute=0).replace(second=0) and
            now() > now().replace(hour=9).replace(minute=0).replace(second=0) %}
            mdi:weather-night
        {% else %}
            mdi:sleep
        {% endif %}
    media_players_active:
      friendly_name: 'Active Media Players'
      value_template: >
        {{ states.media_player
          | rejectattr('state', 'equalto', 'off')
          | rejectattr('state', 'equalto', 'idle')
          | rejectattr('entity_id', 'equalto', 'media_player.spotify')
          | map(attribute ='entity_id')
          | join(', ')
        }}
    living_room_tv:
      friendly_name: 'Living Room TV'
      value_template: '{{ states.remote.living_room_tv.attributes.current_activity }}'
