# - alias: Kitchen Lights Morning
#   trigger:
#   - entity_id: binary_sensor.kitchen_motion
#     from: 'off'
#     platform: state
#     to: 'on'
#   action:
#   - service: light.hue_activate_scene
#     data:
#       group_name: Kitchen
#       scene_name: Energize

# - alias: Turn off kitchen light 10 minutes after last movement
#   trigger:
#   - entity_id: binary_sensor.kitchen_motion
#     platform: state
#     to: off
#     for:
#       minutes: 10
#   action:
#     service: homeassistant.turn_off
#     entity_id: light.kitchen_light
