- alias: Kitchen Lights Morning
  id: '1501284383956'
  trigger:
  - entity_id: binary_sensor.kitchen_motion
    from: 0
    platform: state
    to: 1
  action:
  - service: homeassistant.turn_on
    entity_id: light.kitchen
