homeassistant:
  name: Home
  latitude: ***REMOVED***
  longitude: ***REMOVED***
  elevation: 150
  unit_system: metric
  time_zone: Europe/London
  customize: !include customize.yaml

http:
  api_password: !secret hass_password
  base_url: ***REMOVED***.duckdns.org
  trusted_networks:
  - 127.0.0.1
  - 192.168.0.0/24
  # ssl_certificate: /ssl/fullchain.pem
  # ssl_key: /ssl/privkey.pem
#
# upnp:
#   unit: GBytes
#   external_port: 80

# Enablers
config:
conversation:
frontend:
ios:
logbook:
sun:
updater:

discovery:
  # ignore:
  #   - apple_tv

history: !include history.yaml
recorder:
  purge_days: 7

tts:
  platform: google
  # platform: amazon_polly
  # aws_access_key_id: !secret aws_access_key_id
  # aws_secret_access_key: !secret aws_secret_access_key
  # region_name: eu-west-2

# Includes
automation: !include_dir_merge_list automation
binary_sensor: !include_dir_merge_list binary_sensor
group: !include_dir_merge_named group
input_select: !include input_select.yaml
light: !include lights.yaml
media_player: !include media_player.yaml
nest: !include nest.yaml
remote: !include remotes.yaml
scene: !include scenes.yaml
script: !include scripts.yaml
sensor: !include_dir_merge_list sensor
shell_command: !include shell_commands.yaml
switch: !include switches.yaml
weather: !include weather.yaml
