homeassistant:
  name: Home
  latitude: ***REMOVED***
  longitude: ***REMOVED***
  elevation: 150
  unit_system: metric
  time_zone: Europe/London

http:
  api_password: !secret hass_password

# Enablers
frontend:
config:
updater:
conversation:
history:
logbook:
sun:

discovery:
  ignore:
    - apple_tv

tts:
  platform: google

# Includes
automation: !include_dir_merge_list automation
group: !include_dir_merge_named group
input_select: !include input_select.yaml
light: !include lights.yaml
nest: !include nest.yaml
remote: !include remotes.yaml
scene: !include scenes.yaml
sensor: !include_dir_merge_list sensor
shell_command: !include shell_commands.yaml
switch: !include switches.yaml
weather: !include weather.yaml
