switch.hyperion:
  icon: mdi:lightbulb

switch.living_room_light_tree:
  icon: mdi:lightbulb

light.living_room:
  icon: mdi:lightbulb-outlight

light.kitchen:
  icon: mdi:lightbulb-outlight

light.hallways:
  icon: mdi:hallways

group.all_automations:
  hidden: false

group.all_scripts:
  hidden: false
