switch.hyperion:
  icon: mdi:lightbulb

switch.living_room_light_tree:
  icon: mdi:lightbulb

light.living_room:
  icon: mdi:lightbulb-outline

light.kitchen:
  icon: mdi:lightbulb-outline

light.hallways:
  icon: mdi:lightbulb-outline

group.all_automations:
  hidden: false

group.all_scripts:
  hidden: false
