Living Room:
- light.living_room
- light.living_room_lamp
- light.living_room_spot_1
- light.living_room_spot_2
- light.living_room_spot_3
- media_player.living_room
- media_player.living_room_tv

Kitchen:
- light.kitchen
- light.kitchen_lightstrip
- light.kitchen_spot_1
- light.kitchen_spot_2
- light.kitchen_spot_3
- light.kitchen_spot_4
- light.kitchen_spot_5
- light.kitchen_spot_6
- light.kitchen_lamp_1
- light.kitchen_lamp_2
- media_player.kitchen
- media_player.hear_go

Hallways:
- light.hallways
- light.entrance_hall
- light.entrance_hall_1
- light.entrance_hall_2
- light.first_floor_landing
- light.top_floor_landing

Top Floor:
- light.den_lamp_1
- light.den_lamp_2
- media_player.den
- media_player.bedroom
- media_player.dressing_room
