- alias: Welcome Home
  trigger:
  - entity_id: binary_sensor.entrance_hall_motion
    platform: state
    to: 'on'
  action:
  - service: media_player.volume_set
    entity_id: media_player.hear_go
    data:
      volume_level: 0.8
  - service: tts.amazon_polly_say
    entity_id: media_player.hear_go
    data:
      message: >
        <speak>Welcome home!</speak>
  - service: automation.turn_off
    entity_id: automation.welcome_home
  - delay: 00:00:15
  - service: media_player.volume_set
    entity_id: media_player.hear_go
    data:
      volume_level: 0.3


- alias: Welcome Home Reset
  trigger:
  - entity_id: binary_sensor.entrance_hall_motion
    platform: state
    from: 'on'
    to: 'off'
    for:
      hours: 4
      minutes: 0
      seconds: 0
  condition:
    condition: time
    after: '08:00:00'
    before: '23:00:00'
  action:
  - service: automation.turn_on
    entity_id: automation.welcome_home

- alias: Good Morning
  trigger:
  - entity_id: binary_sensor.kitchen_motion
    platform: state
    to: 'on'
  condition:
    condition: time
    after: '05:00:00'
    before: '09:00:00'
  action:
  - service: media_player.volume_set
    entity_id: media_player.hear_go
    data:
      volume_level: 0.8
  - service: tts.amazon_polly_say
    entity_id: media_player.hear_go
    data:
      message: >
        <speak>Good Morning!</speak>
  - service: automation.turn_off
    entity_id: automation.good_morning
  - service: media_player.volume_set
    entity_id: media_player.hear_go
    data:
      volume_level: 0.3

- alias: Good Morning Reset
  trigger:
  - platform: time
    at: '00:00:00'
  action:
  - service: automation.turn_on
    entity_id: automation.good_morning
