- alias: Welcome home
  trigger:
  - entity_id: binary_sensor.kitchen_motion
    platform: state
    to: 'on'
  action:
  - service: tts.google_say
    entity_id: media_player.kitchen
    data:
      message: 'Welcome home!'
  - service: automation.turn_off
    entity_id: input_boolean.welcome_home
