- alias: "Harmony Change Activity"
  trigger:
  - platform: state
    entity_id: input_select.living_room_tv
  action:
  - service: notify.ios_dphone
    data:
      message: '{{ states.input_select.living_room_tv.state }}'
  - service: remote.turn_on
    data_template:
      entity_id: remote.living_room_tv
      activity: '{{ states.input_select.living_room_tv.state }}'

- alias: "Harmony Update Activity Select"
  trigger:
  - platform: state
    entity_id: sensor.living_room_tv
  action:
  - service: notify.ios_dphone
    data:
      message: '{{ states.sensor.living_room_tv.state }}'
  - service: input_select.select_option
    data_template:
      entity_id: input_select.living_room
      option: '{{ states.sensor.living_room_tv.state }}'
