- alias: "Harmony Change Activity"
  trigger:
  - platform: state
    entity_id: input_select.harmony
  action:
    service: remote.turn_on
    data_template:
      entity_id: remote.living_room_tv
      activity: '{{ trigger.to_state.state }}'

- alias: "Harmony Update Activity Select"
  trigger:
  - platform: sensor
    entity_id: living_room_tv
  action:
    service: remote.turn_on
    data_template:
      entity_id: input_select.living_room
      option: '{{ trigger.to_state.state }}'
