- alias: "Harmony Change Activity"
  trigger:
  - platform: state
    entity_id: input_select.harmony
  action:
  - service: notify.ios_dphone
    data:
      message: '{{ trigger.to_state.state }}'
  - service: remote.turn_on
    data_template:
      entity_id: remote.living_room_tv
      activity: '{{ trigger.to_state.state }}'

- alias: "Harmony Update Activity Select"
  trigger:
  - platform: state
    entity_id: sensor.living_room_tv
  action:
  - service: notify.ios_dphone
    data:
      message: '{{ trigger.to_state.state }}'
  - service: remote.turn_on
    data_template:
      entity_id: input_select.living_room
      option: '{{ trigger.to_state.state }}'
