- alias: "No Effect"
  trigger:
  - platform: state
    entity_id: input_select.hyperion_effect
    to: "None"
  action:
    service: shell_command.hyperion_effect_none

- alias: "Set Effect"
  trigger:
  - platform: state
    entity_id: input_select.hyperion_effect
    from: "None"
  action:
    service: shell_command.hyperion_set_effect
