- alias: Turn off kitchen light X minutes after last movement
  trigger:
  - entity_id: binary_sensor.kitchen_motion
    platform: state
    from: 'on'
    to: 'off'
    for:
      hours: 0
      minutes: 15
      seconds: 0
  action:
  - service: light.turn_off
    entity_id: light.kitchen
    data:
      transition: 15

- alias: Kitchen Lights Morning
  trigger:
  - entity_id: binary_sensor.kitchen_motion
    platform: state
    from: 'off'
    to: 'on'
  action:
  - service: light.hue_activate_scene
    data:
      group_name: Kitchen
      scene_name: Morning
  condition:
    condition: and
    conditions:
    - condition: state
      entity_id: light.kitchen
      state: 'off'
    - condition: time
      after: '05:00:00'
      before: '09:00:00'

- alias: Kitchen Lights Day
  trigger:
  - entity_id: binary_sensor.kitchen_motion
    platform: state
    from: 'off'
    to: 'on'
  action:
  - service: light.hue_activate_scene
    data:
      group_name: Kitchen
      scene_name: Day
  condition:
    condition: and
    conditions:
    - condition: state
      entity_id: light.kitchen
      state: 'off'
    - condition: time
      after: '09:00:00'
    - condition: sun
      before: sunset

- alias: Kitchen Lights Evening
  trigger:
  - entity_id: binary_sensor.kitchen_motion
    platform: state
    from: 'off'
    to: 'on'
  action:
  - service: light.hue_activate_scene
    data:
      group_name: Kitchen
      scene_name: Evening
  condition:
    condition: and
    conditions:
    - condition: state
      entity_id: light.kitchen
      state: 'off'
    - condition: sun
      after: sunset
    - condition: time
      before: '23:00:00'

- alias: Kitchen Lights Night
  trigger:
  - entity_id: binary_sensor.kitchen_motion
    platform: state
    from: 'off'
    to: 'on'
  action:
  - service: light.hue_activate_scene
    data:
      group_name: Kitchen
      scene_name: Night
  condition:
    condition: and
    conditions:
    - condition: state
      entity_id: light.kitchen
      state: 'off'
    - condition: time
      after: '23:00:00'
      before: '05:00:00'
