- alias: Dressing Room Lights Update
  trigger:
  - entity_id: light.dressing_room
    platform: state
    to: 'on'
  action:
  - service: light.hue_activate_scene
    data_template:
      group_name: Dressing Room
      scene_name: '{{ states.sensor.day_phase.state }}'

- alias: Bedroom Lights Update
  trigger:
  - entity_id: light.bedroom
    platform: state
    to: 'on'
  action:
  - service: light.hue_activate_scene
    data_template:
      group_name: Bedroom
      scene_name: '{{ states.sensor.day_phase.state }}'
