- alias: Media Update Active Group
  trigger:
  - entity_id: sensor.media_players_active
    platform: state
  action:
  - service: group.set
    data_template: >
      {% if trigger.to_state.state == '' %}
        {{ {
          'object_id': 'media_players_active',
          'visible': false
        } }}
      {% else %}
        {{ {
          'object_id': 'media_players_active',
          'visible': true,
          'entities': trigger.to_state.state
        } }}
      {% endif %}
