- alias: Media Update Active Group
  trigger:
  - entity_id: sensor.media_players_active
    platform: state
  action:
  - service_template: group.set
    data_template: >
      object_id: media_players_active
      visible: {{ trigger.to_state.state != '' }}
      {% if trigger.to_state.state != '' %}
      entities: {{ trigger.to_state.state }}
      {% endif %}
