- alias: Media Update Active Group
  trigger:
  - entity_id: sensor.media_players_active
    platform: state
  action:
  - service: group.set
    data_template:
      object_id: media_players_active
      visible: >
        {{ trigger.to_state.state != '' }}
      entities: >
        {% if trigger.to_state.state != '' %}
          {{ trigger.to_state.state }}
        {% else %}
          {{ states.group.media_players_active.entity_id }}
        {% endif %}
