- alias: Startup Notification
  trigger:
    platform: event
    event_type: homeassistant_start
  action:
    service: notify.ios_dphone
    data:
      message: 'Home Assistant back online!'

- alias: Shutdown Notification
  trigger:
    platform: event
    event_type: homeassistant_stop
  action:
    service: notify.ios_dphone
    data:
      message: 'Home Assistant is going down!'

- alias: Update notifications
  trigger:
    - platform: state
      entity_id: updater.updater
  action:
    service: notify.ios_dphone
    data:
      message: 'There is a new Home Assistant release available.'

- alias: Travis Build Status
  trigger:
  - platform: state
    entity_id: sensor.travis_build_status
  action:
    service: notify.ios_dphone
    data:
      message: 'Travis build status: {{ states.sensor.travis_build_status.state }}'
