- alias: Startup Notification
  trigger:
    platform: homeassistant
    event: start
  action:
    service: notify.ios_dphone
    data:
      message: 'Home Assistant back online!'

- alias: Shutdown Notification
  trigger:
    platform: homeassistant
    event: shutdown
  action:
    service: notify.ios_dphone
    data:
      message: 'Home Assistant is going down!'

- alias: Update notifications
  trigger:
    - platform: state
      entity_id: updater.updater
  action:
    service: notify.ios_dphone
    data:
      message: 'There is a new Home Assistant release available.'

- alias: Travis Build Status
  trigger:
  - platform: state
    entity_id: sensor.travis_build_status
  condition:
    condition: or
    conditions:
    - condition: template
      value_template: '{{ trigger.from_state.state != "unknown" }}'
    - condition: template
      value_template: '{{ trigger.to_state.state != "unknown" }}'
  action:
  - service: notify.ios_dphone
    data:
      message: 'Travis build status: {{ states.sensor.travis_build_status.state }}'
