- alias: System Startup Notification
  trigger:
    platform: homeassistant
    event: start
  action:
    service: notify.ios_dphone
    data:
      message: 'Home Assistant back online!'

- alias: System Shutdown Notification
  trigger:
    platform: homeassistant
    event: shutdown
  action:
    service: notify.ios_dphone
    data:
      message: 'Home Assistant is going down!'

- alias: System Update notifications
  trigger:
    - platform: state
      entity_id: updater.updater
  action:
    service: notify.ios_dphone
    data:
      message: 'There is a new Home Assistant release available.'

- alias: System Travis Build Status
  trigger:
  - platform: template
    value_template: >
      {{ is_state('sensor.travis_build_status', 'passed')
      or is_state('sensor.travis_build_status', 'failed')
      }}
  action:
  - service: notify.ios_dphone
    data:
      message: 'Travis build status: {{ states.sensor.travis_build_status.state }}'
