- alias: Travis Build Status
  trigger:
  - platform: state
    entity_id: sensor.travis_build_status
  action:
    service: notify.ios_dphone
    data:
      title: 'Travis Build Status...'
      message: {{ trigger.to_state.state }}

- alias: Apply New Config From Git
  trigger:
  - platform: state
    entity_id: sensor.travis_build_status
    to: 'finished'
  action:
    - service: notify.ios_dphone
      data:
        title: 'Updating Config'
        message: 'Restarting Home Assistant...'
    - service: shell_command.update_from_git
