- alias: Startup Notification
  trigger:
    platform: time
    at: '19:00:00'
  # condition:
  #   condition: time
  #   weekday:
  #     - sun
  action:
    service: notify.ios_dphone
    data_template:
      title: 'Congratulations, you made it through another week!'
      message: >
        Here's some stats from the week:-

        Music Listened To: {{ states.sensor.music_listened_to_this_week.state }} hrs

        Total TV Watched: {{ states.sensor.total_tv_watched_this_week.state }} hrs
        Sky TV Watched: {{ states.sensor.sky_tv_watched_this_week.state }} hrs
        Shield TV Watched: {{ states.sensor.shield_tv_watched_this_week.state }} hrs

        PlayStation 4 Played: {{ states.sensor.playstation_4_played_this_week.state }} hrs
        Steam Played: {{ states.sensor.steam_games_played_this_week.state }} hrs

        Kitchen Heater On: {{ states.sensor.kitchen_heater_on_this_week.state }} hrs
