- alias: Den Lamp Off
  trigger:
  - entity_id: media_player.playstation_4
    platform: state
    to: 'off'
    for:
      hours: 0
      minutes: 5
      seconds: 0
  action:
  - service: light.turn_off
    entity_id: light.den
    data:
      transition: 15

- alias: Den Lamp On
  trigger:
  - entity_id: media_player.playstation_4
    platform: state
  condition:
    condition: template
    value_template: >
      {{ states.media_player.playstation_4.state != 'off' }}
  action:
  - service: light.hue_activate_scene
    data_template:
      group_name: Den
      scene_name: >
        {% if states.media_player.playstation_4.attributes.source == 'Destiny 2' %}
          D2 {{ states.sensor.destiny2.state }}
        {% elif states.media_player.playstation_4.attributes.source == 'EVE' %}
          PS4 VR
        {% else %}
          PS4 Default
        {% endif %}

- alias: Den Lamp Destiny 2 Sync
  trigger:
  - entity_id: sensor.destiny2
    platform: state
  condition:
    condition: template
    value_template: >
      {{ states.media_player.playstation_4.attributes.source == 'Destiny 2' }}
  action:
  - service: light.hue_activate_scene
    data_template:
      group_name: Den
      scene_name: >
        D2 {{ states.sensor.destiny2.state }}
