- alias: Den Lamp Off
  trigger:
  - entity_id: media_player.playstation_4
    platform: state
    to: 'off'
    for:
      hours: 0
      minutes: 5
      seconds: 0
  action:
  - service: light.turn_off
    entity_id: light.den
    data:
      transition: 15

- alias: Den Lamp On
  trigger:
  - entity_id: media_player.playstation_4
    platform: state
  condition:
    condition: and
    conditions:
    - condition: template
      value_template: >
        {{ states.media_player.playstation_4.state != 'off' }}
    - condition: template
      value_template: >
        {{ states.sensor.day_phase.state == 'Evening'
        or states.sensor.day_phase.state == 'Night'
        }}
  action:
  - service: light.hue_activate_scene
    data_template:
      group_name: Den
      scene_name: >
        {% if states.media_player.playstation_4.attributes.source == 'Destiny 2' %}
          {% if states.sensor.destiny_2_subclass_element.state == 'Arc' %}
            D2 Arc
          {% elif states.sensor.destiny_2_subclass_element.state == 'Void' %}
            D2 Void
          {% else %}
            D2 Solar
          {% endif %}
        {% else %}
          PS4 Default
        {% endif %}

- alias: Den Lamp Destiny 2 Sync
  trigger:
  - entity_id: sensor.destiny_2_subclass_element
    platform: state
  condition:
    condition: template
    value_template: >
      {{ states.media_player.playstation_4.attributes.source == 'Destiny 2' }}
  action:
  - service: light.hue_activate_scene
    data_template:
      group_name: Den
      scene_name: >
        {% if states.sensor.destiny_2_subclass_element.state == 'Arc' %}
          D2 Arc
        {% elif states.sensor.destiny_2_subclass_element.state == 'Void' %}
          D2 Void
        {% else %}
          D2 Solar
        {% endif %}
