speakers_everything:
  name: Speakers
  icon: mdi:speaker-wireless
  entities:
  - media_player.every_speaker
  - media_player.every_speaker_but_tv

speakers_ground_floor:
  name: Speakers
  icon: mdi:speaker-wireless
  entities:
  - media_player.kitchen_speakers
  - media_player.kitchen_speaker
  - media_player.portable_speaker

speakers_middle_floor:
  name: Speakers
  icon: mdi:speaker-wireless
  entities:
  - media_player.living_room_speakers

speakers_top_floor:
  name: Speakers
  icon: mdi:speaker-wireless
  entities:
  - media_player.top_floor_speakers
  - media_player.den_speakers
  - media_player.bedroom_speakers
  - media_player.bedroom_google_home
  - media_player.dressing_room_speakers
