- alias: Everything Off
  trigger:
  - platform: state
    entity_id: binary_sensor.house_motion
    to: 'on'
    for:
      hours: 1
      minutes: 0
      seconds: 0
  action:
  - service: scene.turn_on
    entity_id: scene.everything_off
  - service: notify.ios_dphone
    data:
      message: 'Turning everything off!'
