- alias: Porch Light Auto On
  trigger:
  - platform: sun
    event: sunset
  action:
  - service: light.turn_on
    entity_id: light.porch

- alias: Porch Light Auto Off
  trigger:
  - platform: state
    entity_id: sun.sun
    to: 'above_horizon'
  action:
  - service: light.turn_off
    entity_id: light.porch

- alias: Porch Light Keep On
  trigger:
  - platform: state
    entity_id: light.porch
    to: 'off'
  condition:
    condition: state
    entity_id: sun.sun
    state: below_horizon
  action:
  - service: light.turn_on
    entity_id: light.porch
  