- alias: System Startup Notification
  trigger:
    platform: homeassistant
    event: start
  action:
  - service: notify.ios_dphone
    data_template:
      message: >
        Home Assistant back online! {{ "\uD83E\uDD29" }}
  - delay:
      seconds: 30
  - service: switch.turn_off
    entity_id: switch.git_pull

- alias: System Shutdown Notification
  trigger:
    platform: homeassistant
    event: shutdown
  action:
  - service: notify.ios_dphone
    data_template:
      message: >
        Home Assistant is going down! {{ "\uD83D\uDE34" }}

- alias: System Update notifications
  trigger:
    - platform: state
      entity_id: updater.updater
  action:
  - service: notify.ios_dphone
    data:
      message: 'There is a new Home Assistant release available.'

- alias: System Travis Build Status
  trigger:
  - platform: state
    entity_id: sensor.travis_build_status
    from: 'started'
    to: 'failed'
  action:
  - service: notify.ios_dphone
    data_template:
      message: >
        Travis build failed! {{ "\uD83E\uDD2C" }}

- alias: System Travis Build Passed
  trigger:
  - platform: state
    entity_id: sensor.travis_build_status
    from: 'started'
    to: 'passed'
  action:
  - service: notify.ios_dphone
    data_template:
      message: >
        Travis build passed! {{ "\uD83D\uDC4D" }}
      
  - service: switch.turn_on
    entity_id: switch.git_pull
  
