- platform: template
  sensors:
    house_thermostat_active:
      value_template: >
        {{ (states.sensor.house_thermostat_temperature.state | int) < (states.sensor.house_thermostat_target.state | int)
        and (states.sensor.house_thermostat_operation_mode.state == "heat")
        }}
