- platform: template
  sensors:
    house_motion:
      value_template: >
        {{ 
          states.binary_sensor.entrance_hall_motion.state == 'on' or
          states.binary_sensor.kitchen_motion.state == 'on' or
          states.binary_sensor.living_room_motion.state == 'on' or
          states.binary_sensor.top_floor_motion.state == 'on' 
        }}
