- platform: template
  sensors:
    house_motion:
      friendly_name: 'House Motion'
      value_template: >
        {{ 
          states.binary_sensor.entrance_hall_motion.state == 'on' or
          states.binary_sensor.kitchen_motion.state == 'on' or
          states.binary_sensor.living_room_motion.state == 'on' or
          states.binary_sensor.top_floor_motion.state == 'on' 
        }}
    kitchen_motion:
      friendly_name: 'Kitchen Motion'
      value_template: >
        {{
          states.binary_sensor.kitchen_motion.state == 'on'
        }}
    living_room_motion:
      friendly_name: 'Living Room Motion'
      value_template: >
        {{
          states.binary_sensor.living_room_motion.state == 'on'
        }}
    top_floor_motion:
      friendly_name: 'Top Motion'
      value_template: >
        {{
          states.binary_sensor.top_floor_motion.state == 'on'
        }}
    entrance_hall_motion:
      friendly_name: 'Entrance Hall Motion'
      value_template: >
        {{
          states.binary_sensor.entrance_hall_motion.state == 'on'
        }}
